services:
  postgres:
    image: postgres:alpine
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url_shortener
    ports:
      - 25432:5432

  url_shortener:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
