services:
  postgres:
    image: postgres:alpine
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url_shortener
    ports:
      - 25432:5432

  redis:
    image: bitnami/redis:latest
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 26379:6379

  url_shortener:
    image: vinchent123/url_shortener:v0.0.1
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - 23000:3000

  url_deleter:
    image: vinchent123/url_deleter:v0.0.1
    restart: always
    deploy:
      mode: replicated
      replicas: 1

