services:
  postgres:
    image: postgres:alpine
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url_shortener
    ports:
      - 25432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 28080:8080
